spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.auto: validate
  datasource:
    driverClassName: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:kakaopay}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: kakaopay
    password: kakaopay
  liquibase:
    enabled: true
